trigger:
  branches:
    include:
      - main

parameters:
  - name: environment
    displayName: "Target Environment"
    type: string
    default: 'test'
    values:
      - test
      - prod

variables:
  ENV: ${{ parameters.environment }}

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Setup
    displayName: 'Setup Environment'
    jobs:
      - job: SetupJob
        displayName: 'Install and Setup Test Data'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              npm ci
              npm run setup:$(ENV)
            displayName: 'Run setup.js'

  - stage: Run
    displayName: 'Run Newman Tests'
    dependsOn: Setup
    jobs:
      - job: RunTests
        displayName: 'Run Tests with Newman'
        steps:
          - script: |
              npm run run:$(ENV)
            displayName: 'Execute Newman Tests'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'allure-results'
              artifactName: 'allure-results'
              publishLocation: 'Container'
            displayName: 'Publish Allure Results'